#!/usr/bin/env -S python3 -B
import argparse
from nmapy.parser import Parser

def main():
    parser = argparse.ArgumentParser(description='Messenger command line tool.')
    parser.add_argument("--file", required=True, help="Nmap output file")
    parser.add_argument("--delimiter", default='\n', help="Delimiter for output")
    parser.add_argument('--display', choices=['hosts', 'livehosts', 'liveports', 'webhosts', 'webports', 'smbhosts', 'sqlhosts', 'sqlports'], default='hosts',
                        help='What to display. Options: hosts, webhosts, webports, smbhosts, sqlhosts, sqlports. Default is hosts.')

    args = parser.parse_args()

    # Initialize parser and call the appropriate display function
    p = Parser(args.file, args.delimiter)
    display_function = p.display_functions[args.display]
    display_function()

if __name__ == '__main__':
    main()
